plugins {
    id 'org.springframework.boot' version '3.3.0' apply false
}

subprojects {
    apply plugin: 'java'

    group = 'com.matching'
    version = '0.0.1-SNAPSHOT'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation platform("org.springframework.boot:spring-boot-dependencies:3.3.0")
        annotationProcessor platform("org.springframework.boot:spring-boot-dependencies:3.3.0")
        
        compileOnly 'org.projectlombok:lombok:1.18.32'
        annotationProcessor 'org.projectlombok:lombok:1.18.32'
    }
}
